# Generated by Django 4.2.16 on 2025-12-17 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("hrapps", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="application",
            options={
                "permissions": (
                    ("approve_application", "Can approve visible applications"),
                    ("reject_application", "Can reject visible applications"),
                    ("create_new_application", "Can view and send applications"),
                    ("view_all_applications", "Can view all applications"),
                    (
                        "view_corp_applications",
                        "Can view apps to main characters corporation",
                    ),
                    (
                        "view_alt_corp_applications",
                        "Can view apps to any corporation your a member of",
                    ),
                )
            },
        ),
        migrations.CreateModel(
            name="FilterDataSource",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField(editable=False)),
                (
                    "content_type",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "default_permissions": [],
            },
        ),
    ]
