# Generated by Django 4.2.16 on 2025-12-17 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hrapps", "0002_alter_application_options_filterdatasource"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationform",
            name="filters",
            field=models.ManyToManyField(to="hrapps.filterdatasource"),
        ),
    ]
